---
title: "Untitled"
output: html_document
date: "2025-11-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r} 

###############################
### Load libraries and data ###
###############################

# Libraries
setwd(here())
source("scraper_functions.R")
library(tidyverse)
library(stringi)


### Data ###

# Load schedule
schedule <- index_schedule(85, append = T)


# Create opponent map
opp_map <- schedule %>%
  select(season, gameid, homeTeam, awayTeam)

# Load scoring summary files
boxscores <- file_scoring_summary(85, append = T)
boxscores <- boxscores %>% 
  filter(Game.Id %in% schedule$gameid)

# Stats for player maps
stats <- index_player_stats(85, append = TRUE)
player_map <- stats %>%
  mutate(name = stri_trans_general(name, "Latin-ASCII")) %>%
  group_by(id, season) %>%
  summarise(name_g = name,
            name_a1 = name,
            name_a2 = name,
            pos_g = position,
            pos_a1 = position,
            pos_a2 = position)

# Load team colors
team_meta <- index_meta(85)
team_colors <- team_meta$colors_primary
names(team_colors) <- team_meta$abbreviation
```




```{r}

##########################################################
### Format 3 individual dataframes for duo combiations ###
##########################################################

# Filter boxscores for at least 1 assist
boxscores_filtered <- boxscores %>%
  filter(!(is.na(Assist.1))) %>%
  left_join(select(player_map, id, name_g, season, pos_g), by = c("Scorer" = "id", "season")) %>%
  left_join(select(player_map, id, name_a1, season, pos_a1), by = c("Assist.1" = "id", "season")) %>%
  left_join(select(player_map, id, name_a2, season, pos_a2), by = c("Assist.2" = "id", "season")) %>%
  left_join(opp_map, by = c("season", "Game.Id" = "gameid")) %>%
  mutate(opp = case_when(TeamId == homeTeam ~ awayTeam,
                         TeamId == awayTeam ~ homeTeam)) %>%
  select(-homeTeam, -awayTeam)


### Create 3 different duo boxscore files to later merge ###

# goal scorer and primary assist
boxscores_1 <- boxscores_filtered %>%
  select(season, TeamId, opp, name_g, name_a1, pos_g, pos_a1) %>%
  rowwise() %>%
  mutate(duo = paste(sort(c(name_g, name_a1)), collapse = ", "),
         duo_pos = paste(c(pos_g, pos_a1), collapse = ", ")) 


# goal scorer and 2nd assist 
boxscores2 <- boxscores_filtered %>%
  filter(!(is.na(name_a2))) %>%
  select(season, TeamId, opp, name_g, name_a2, pos_g, pos_a2) %>%
  rowwise() %>%
  mutate(duo = paste(sort(c(name_g, name_a2)), collapse = ", "),
         duo_pos = paste(c(pos_g, pos_a2), collapse = ", ")) 


  
# both assists
boxscores3 <- boxscores_filtered %>%
  filter(!(is.na(name_a1)) & !(is.na(name_a2))) %>%
  select(season, TeamId, opp, name_a1, name_a2, pos_a1, pos_a2) %>%
  rowwise() %>%
  mutate(duo = paste(sort(c(name_a1, name_a2)), collapse = ", "),
         duo_pos = paste(c(pos_a1, pos_a2), collapse = ", ")) 



# merged boxscores
merged_duos <- bind_rows(boxscores_1, boxscores2, boxscores3) %>%
  select(season, TeamId, duo, opp, duo_pos, name_g, name_a1, name_a2) %>%
  left_join(select(team_meta, id, abbreviation), by = c("TeamId" = "id")) %>%
  left_join(select(team_meta, id, abbreviation), by = c("opp" = "id")) %>%
  rename("abbreviation" = "abbreviation.x",
         "opp_abbreviation" = "abbreviation.y")


```




```{r}

#################################
### Top duos of all time plot ###
#################################

top_duo_all_time <- merged_duos %>%
  group_by(duo, abbreviation) %>%
  summarize(n = n()) %>%
  group_by(duo) %>%
  mutate(total = sum(n)) %>%
  ungroup() %>%
  arrange(desc(total)) %>%
  mutate(duo = factor(duo, levels = unique(duo))) %>%
  mutate(rank = as.numeric(duo)) %>%
  filter(rank <= 25)


ggplot(top_duo_all_time, aes(x = n, y = fct_rev(duo), fill = abbreviation)) +
  geom_col(col = "black",
           show.legend = F) +
  geom_text(aes(label = abbreviation),
            col = "white",
            position = position_stack(vjust = .5),
            size = 3) +
  theme_bw(base_size = 14) +
  theme(panel.grid = element_blank()) +
  scale_fill_manual(values = team_colors) +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_discrete(expand = c(0,0)) +
  labs(x = "Combined goals", y = NULL)
```





```{r}


###########################################
### Top defensman duos of all time plot ###
###########################################

top_d_duo_all_time <- merged_duos %>%
  filter(duo_pos %in% c("RD, LD", "RD, RD", "LD, RD", "LD, LD")) %>%
  group_by(duo, abbreviation) %>%
  summarize(n = n()) %>%
  group_by(duo) %>%
  mutate(total = sum(n)) %>%
  ungroup() %>%
  arrange(desc(total)) %>%
  mutate(duo = factor(duo, levels = unique(duo))) %>%
  mutate(rank = as.numeric(duo)) %>%
  filter(rank <= 25)


ggplot(top_d_duo_all_time, aes(x = n, y = fct_rev(duo), fill = abbreviation)) +
  geom_col(col = "black",
           show.legend = F) +
  geom_text(aes(label = abbreviation),
            col = "white",
            position = position_stack(vjust = .5),
            size = 3) +
  theme_bw(base_size = 14) +
  theme(panel.grid = element_blank()) +
  scale_fill_manual(values = team_colors) +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_discrete(expand = c(0,0)) +
  labs(x = "Combined goals", y = NULL)
```







```{r}
##############################
### Top duos for each team ###
##############################

top_duo_per_team <- merged_duos %>%
  group_by(duo, abbreviation) %>%
  summarize(n = n()) %>%
  group_by(abbreviation) %>%
  arrange(abbreviation, desc(n)) %>%
  mutate(duo_label = paste0(duo, " (", abbreviation, ")")) %>%
  mutate(duo_label = factor(duo_label, levels = duo_label)) %>%
  mutate(rank = row_number()) %>%
  filter(rank <= 3) %>%
  ungroup() %>%
  mutate(facet = case_when(row_number() <= 36 ~ 1,
                           TRUE ~ 2))


ggplot(top_duo_per_team, aes(x = n, y = fct_rev(duo_label), fill = abbreviation, alpha = factor(rank))) +
  geom_col(col = "black",
           show.legend = F) +
  facet_wrap(.~ facet, scales = "free_y") +
  scale_fill_manual(values = team_colors) +
  scale_alpha_manual(values = c(1,.8,.6)) +
  theme_bw(base_size = 14) +
  theme(panel.grid = element_blank(),
        strip.text = element_blank(),
        strip.background = element_blank(),
        axis.ticks.y = element_blank()) +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_discrete(expand = c(0,0)) +
  labs(x = "Combined goals", y = NULL)
```



```{r}
##################################
### Top duos against each team ###
##################################


### First, find the top 3 duos per team, to later filter
### Not sure how to directly filter
top_duo_against_team_rank <- merged_duos %>%
  group_by(duo, opp_abbreviation) %>%
  summarize(n = n()) %>%
  mutate(duo_label = paste0(duo, " (", opp_abbreviation, ")")) %>%
  arrange(opp_abbreviation, desc(n)) %>%
  group_by(opp_abbreviation) %>%
  mutate(rank = row_number()) %>%
  filter(rank <= 3)


top_duo_against_team <- merged_duos %>%
  group_by(duo, opp_abbreviation, abbreviation) %>%
  summarize(n = n()) %>%
  group_by(duo, opp_abbreviation) %>%
  mutate(tot = sum(n)) %>%
  arrange(opp_abbreviation, desc(tot)) %>%
  group_by(opp_abbreviation) %>%
  mutate(duo_label = paste0(duo, " (", opp_abbreviation, ")")) %>%
  mutate(duo_label = factor(duo_label, levels = unique(duo_label))) %>%
  filter(duo_label %in% top_duo_against_team_rank$duo_label)


ggplot(top_duo_against_team, aes(x = n, y = fct_rev(duo_label), fill = abbreviation))+
  geom_col(col = "black",
           show.legend = F) +
  facet_wrap(.~ opp_abbreviation, 
             scales = "free_y",
             ncol = 2, 
             dir = "v") +
  scale_fill_manual(values = team_colors) +
  theme_bw(base_size = 12) +
  theme(panel.grid = element_blank(),
        strip.background = element_blank(),
        strip.text = element_text(face = "bold")) +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_discrete(expand = c(0,0),
                   breaks = top_duo_against_team$duo_label,
                   labels = top_duo_against_team$duo) +
  labs(x = "Combined goals", y = NULL)
```




```{r}
################################
### Top duos for each season ###
################################

top_duo_per_season <- merged_duos %>%
  group_by(duo, season) %>%
  summarize(n = n(),
            team = abbreviation[1]) %>%
  group_by(season) %>%
  arrange(season, desc(n)) %>%
  mutate(duo_label = paste0(duo, " (", team, ")")) %>%
  mutate(duo_label = factor(duo_label, levels = duo_label)) %>%
  mutate(rank = row_number()) %>%
  ungroup() %>%
  mutate(label = case_when(rank <= 3 ~ TRUE,
                           TRUE ~ FALSE),
         y_pos = 80-(10*(rank-1)))


ggplot(top_duo_per_season, aes(x = rank, y = n)) +
  geom_point(aes(shape = label,
                 fill = team,
                 size = label),
             show.legend = F) +
  facet_wrap(.~ season) +
  geom_label(data = filter(top_duo_per_season, label == TRUE),
             aes(label = duo_label,
                 x = 150,
                 y = y_pos,
                 col = team),
             size = 3,
             hjust = 0,
             show.legend = F) +
  scale_shape_manual(values = c(16, 21)) +
  scale_fill_manual(values = team_colors) +
  scale_size_manual(values = c(1,3)) +
  scale_color_manual(values = team_colors) +
  geom_segment(data = filter(top_duo_per_season, label == TRUE),
               aes(x = rank,
                   xend = 150,
                   y = n,
                   yend = y_pos,
                   col = team),
               show.legend = F) +
  theme_bw() +
  theme(panel.grid = element_blank(),
        strip.background = element_blank(),
        strip.text = element_text(face = "bold")) +
  labs(x = "Duo rank", y = "Combined goals")
         
```





```{r}
#######################################
### Highest percent of total points ###
#######################################

# Get career totals first
# Remove the one season of the Lucas Raymond name duplicate, oh well

career_totals <- stats %>%
  mutate(name = stri_trans_general(name, "Latin-ASCII")) %>%
  filter(!(name == "Lucas Raymond" & season == 68)) %>%
  filter(season >= 66) %>%
  group_by(name) %>%
  summarise(g = sum(goals),
            a = sum(assists),
            p = sum(points)) 

  



merged_duos_long <- merged_duos %>%
  group_by(duo) %>%
  mutate(duo_goals = n()) %>%
  mutate(assist = case_when(is.na(name_a1) ~ name_a2,
                            is.na(name_a2) ~ name_a1)) %>%
  select(-duo_pos, -name_a1, -name_a2) %>%
  pivot_longer(cols = c(name_g, assist),
               names_to = "role",
               values_to = "name") %>%
  left_join(career_totals, by = "name") %>%
  group_by(name) %>%
  mutate(perc_duo = duo_goals/p) %>%
  
  #filter for players with at least 100 career points
  filter(p >= 200)


duo_long_plot <- merged_duos_long %>%
  group_by(duo, name) %>%
  summarise(p = p[1],
            duo_goals = duo_goals[1],
            perc_duo = perc_duo[1])


ggplot(duo_long_plot, aes(x = duo_goals, y = p)) +
  geom_jitter() +
  theme_bw(base_size = 16) +
  theme(panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.line = element_line())


top_duo_perc <- duo_long_plot %>%
  ungroup() %>%
  mutate(label = paste0("(",name, duo)) %>%
  arrange(desc(perc_duo)) %>%
  filter(row_number() <= 25) %>%
  mutate(label = factor(label, levels = label))

ggplot(top_duo_perc, aes(x = p, y = fct_rev(label))) +
  geom_col(aes(fill = perc_duo),
           alpha = .5,
           col = "black",
           show.legend = F) +
  geom_col(aes(x = duo_goals,
               fill = perc_duo),
           col = "black",
           show.legend = F) +
  
  scale_y_discrete(breaks = top_duo_perc$label, 
                   labels = top_duo_perc$name,
                   expand = c(0,0)) +
  scale_fill_gradient(low = "#56B1F7", high = "#132B43") +
  scale_x_continuous(expand = c(0,0)) +
  
  geom_text(aes(x = 1100, label = paste0("(", duo, ")")),
            hjust = 1) +
  geom_text(aes(label = paste0(round(perc_duo, 2), "%"),
                x = duo_goals/2),
            col = ifelse(top_duo_perc$perc_duo > .52, "white", "black")) +
  
  geom_text(aes(x=1125, label="")) +
  
  theme_bw(base_size = 14) +
  theme(panel.grid = element_blank(),
        axis.ticks.y = element_blank()) +
  labs(x = "Total points (Duo | Solo)", y = NULL)
```



```{r}

####################################
### Unassisted and empty netters ###
####################################

### Unassisted goals
unassisted_goals <- boxscores %>%
  filter(is.na(Assist.1) & is.na(Assist.2)) %>%
  left_join(select(player_map, id, season, name_g), by = c("Scorer" = "id", "season"))

unassisted_leaders <- unassisted_goals %>%
  group_by(Scorer) %>%
  summarise(name = last(name_g),
            n = n())



### Empty net leaders
empty_netters <- boxscores %>% 
  filter(grepl(pattern = "ENG",
               x = Note)) %>%
  left_join(select(player_map, id, season, name_g), by = c("Scorer" = "id", "season"))



empty_net_leaders <- empty_netters %>% 
  group_by(Scorer) %>%
  summarise(name = last(name_g),
            n = n())
```

